language: android

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./wait_for_emulator
  # Going to project directory
  - cd Omega-Splicer


android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-22.0.1

    # The SDK version used to compile your project
    - android-22

    # Personnal extra
    - extra-android-support

    - sys-img-armeabi-v7a-android-19